data:
  StanfordCars:
    Masks:
      initial_lr: 0.0001
      milestones: [ 15, 30 ]
      optimizer: Adam
      threshold: 0.005
      bs: 32
      epochs: 30
      weight_modulation_factor: [ 4, 4 ]
      wd: 0.00001
      reg: .0
    Modulation:
      initial_lr: 0.01
      milestones: [ 15, 30 ]
      optimizer: Adam
      weight_modulation_factor: [ 1, 1 ]
      threshold: 0.005
      bs: 32
      epochs: 30
      interpolation: bicubic
      reg: 0.0000
      wd: .0
    Full:
      initial_lr: 0.0001
      milestones: [ 15, 30 ]
      optimizer: Adam
      threshold: 0.005
      bs: 32
      epochs: 30
      weight_modulation_factor: [ 1,1 ]
      reg: .0
      wd: .0
    Classifier_Only:
      initial_lr: 0.001
      milestones: [ 15, 30 ]
      optimizer: Adam
      weight_modulation_factor: [ 5,5 ]
      threshold: 0.005
      bs: 32
      epochs: 30
      interpolation: bicubic
      reg: .0
      wd: .0
    LWF:
      initial_lr: 0.0001
      milestones: [ 15, 30 ]
      optimizer: Adam
      weight_modulation_factor: [ 6,6 ]
      threshold: 0.005
      bs: 32
      epochs: 30
      wd: 0.0
      interpolation: bicubic
      reg: 5000
  Flowers:
    Masks:
      initial_lr: 0.0001
      milestones: [ 15, 30 ]
      optimizer: Adam
      threshold: 0.005
      bs: 32
      epochs: 30
      weight_modulation_factor: [ 4, 4 ]
      wd: .00001
      reg: .0
    Full:
      initial_lr: 0.0001
      milestones: [ 15, 30 ]
      optimizer: Adam
      threshold: 0.005
      bs: 32
      epochs: 30
      weight_modulation_factor: [ 4,4 ]
      wd: .0
    LWF:
      initial_lr: 0.001
      milestones: [ 15, 30 ]
      optimizer: Adam
      weight_modulation_factor: [ 6,6 ]
      threshold: 0.005
      bs: 32
      epochs: 30
      wd: 0.0
      interpolation: bicubic
      reg: 70000
    Modulation:
      initial_lr: 0.01
      reg: .00001
      milestones: [ 15, 30 ]
      optimizer: Adam
      weight_modulation_factor: [ 6,6 ]
      threshold: 0.005
      bs: 32
      epochs: 30
      wd: 0.0
      interpolation: bicubic
      factor: .1
    Classifier_Only:
      initial_lr: 0.0001
      milestones: [ 15, 30 ]
      optimizer: Adam
      learnable_downsample: True
      weight_modulation_factor: [ 5,5 ]
      threshold: 0.005
      bs: 32
      epochs: 30
      interpolation: bicubic
      num_blocks: [ ]
      groups: [ ]
      wd: .0
      reg: 0.0001
  CUBS:
    Masks:
      initial_lr: 0.0001
      milestones: [ 15 ]
      optimizer: Adam
      learnable_downsample: True
      threshold: 0.005
      bs: 32
      epochs: 30
      weight_modulation_factor: [ 4,4 ]
      mask_modulation_factor: [ 1, 1 ]
      wd: 0.00001
      reg: .0
    Full:
      initial_lr: 0.001
      milestones: [ 15, 30 ]
      optimizer: Adam
      learnable_downsample: True
      threshold: 0.005
      bs: 32
      epochs: 30
      weight_modulation_factor: [ 4,4,1,1 ]
    Modulation:
      initial_lr: 0.001
      milestones: [ 15, 30 ]
      optimizer: Adam
      learnable_downsample: True
      weight_modulation_factor: [ 5,5 ]
      mask_modulation_factor: [ 1, 1 ]
      threshold: 0.005
      bs: 32
      epochs: 30
      interpolation: bicubic
      num_blocks: [ ]
      groups: [ ]
      wd: .0
      reg: 0.0000
      factor: .1
    Classifier_Only:
      initial_lr: 0.001
      reg: .0
      factor: .1
      milestones: [ 15 ]
      optimizer: Adam
      learnable_downsample: True
      weight_modulation_factor: [ 5,5 ]
      weight_modulation_factors: [ [ 4,4 ],[ 9,9 ] ]
      mask_modulation_factor: [ 1, 1 ]
      threshold: 0.005
      bs: 32
      epochs: 30
      interpolation: bicubic
      num_blocks: [ ]
      groups: [ ]
      wd: .0
    LWF:
      initial_lr: 0.001
      milestones: [ 15, 30 ]
      optimizer: Adam
      learnable_downsample: True
      weight_modulation_factor: [ 6,6 ]
      weight_modulation_factors: [ [ 4,4 ] ]
      groups: [ ]
      num_blocks: [ ]
      mask_modulation_factor: [ 1, 1 ]
      threshold: 0.005
      bs: 32
      epochs: 30
      wd: 0.0
      interpolation: bicubic
      reg: 400000
      factor: .1
  Food:
    Masks:
      initial_lr: 0.0001
      milestones: [ 15 ]
      optimizer: Adam
      learnable_downsample: True
      threshold: 0.005
      bs: 96
      epochs: 30
      weight_modulation_factor: [ 4, 4 ]
      mask_modulation_factor: [ 1, 1 ]
      weight_modulation_factors: [ [ 4, 4 ] ]
      wd: 0.00001
    Full:
      initial_lr: 0.001
      milestones: [ 15 ]
      optimizer: Adam
      learnable_downsample: True
      threshold: 0.005
      bs: 96
      epochs: 30
      weight_modulation_factor: [ 4,4 ]
      mask_modulation_factor: [ 1, 1 ]
      weight_modulation_factors: [ [ 4, 4 ] ]
      wd: .0
    Modulation:
      initial_lr: 0.01
      milestones: [ 15, 30 ]
      optimizer: Adam
      learnable_downsample: True
      weight_modulation_factor: [ 5,5 ]
      mask_modulation_factor: [ 1, 1 ]

      threshold: 0.005
      bs: 96
      epochs: 30
      interpolation: bicubic
    Classifier_Only:
      initial_lr: 0.0001
      milestones: [ 15, 30 ]
      optimizer: Adam
      learnable_downsample: True
      weight_modulation_factor: [ 5,5 ]
      weight_modulation_factors: [ [ 4,4 ],[ 9,9 ] ]
      mask_modulation_factor: [ 1, 1 ]
      threshold: 0.005
      bs: 32
      epochs: 30
      interpolation: bicubic
      num_blocks: [ ]
      groups: [ ]
      wd: .0
  WikiArt:
    Masks:
      initial_lr: 0.0001
      milestones: [ 15 ]
      optimizer: Adam
      learnable_downsample: True
      threshold: 0.005
      bs: 32
      epochs: 30
      weight_modulation_factor: [ 4, 4 ]
      weight_modulation_factors: [ [ 4, 4 ] ]
      mask_modulation_factor: [ 1, 1 ]
      groups: [ ]
      num_blocks: [ ]
      wd: .0
    Full:
      initial_lr: 0.001
      milestones: [ 15, 30 ]
      optimizer: Adam
      learnable_downsample: True
      threshold: 0.005
      bs: 32
      epochs: 30
      weight_modulation_factor: [ 4, 4 ]
      weight_modulation_factors: [ [ 4, 4 ] ]
      mask_modulation_factor: [ 1, 1 ]
      wd: .0
    Modulation:
      initial_lr: 0.01
      milestones: [ 15, 30 ]
      optimizer: Adam
      learnable_downsample: True
      weight_modulation_factor: [ 5,5 ]
      mask_modulation_factor: [ 1, 1 ]
      threshold: 0.005
      bs: 32
      epochs: 30
      interpolation: bicubic
      groups: [ ]
      num_blocks: [ ]
    Classifier_Only:
      initial_lr: 0.001
      milestones: [ 15, 30 ]
      optimizer: Adam
      learnable_downsample: True
      weight_modulation_factor: [ 5,5 ]
      weight_modulation_factors: [ [ 4,4 ],[ 9,9 ] ]
      mask_modulation_factor: [ 1, 1 ]
      threshold: 0.005
      bs: 32
      epochs: 30
      interpolation: bicubic
      num_blocks: [ ]
      groups: [ ]
      wd: .0
    LWF:
      initial_lr: 0.001
      milestones: [ 15, 30 ]
      optimizer: Adam
      learnable_downsample: True
      weight_modulation_factor: [ 6,6 ]
      weight_modulation_factors: [ [ 4,4 ] ]
      groups: [ ]
      num_blocks: [ ]
      mask_modulation_factor: [ 1, 1 ]
      threshold: 0.005
      bs: 32
      epochs: 30
      wd: 0.0
      interpolation: bicubic
      reg: 70000
      factor: .1
  Sketches:
    Masks:
      initial_lr: 0.0001
      milestones: [ 15 ]
      optimizer: Adam
      learnable_downsample: True
      threshold: 0.005
      bs: 32
      epochs: 30
      weight_modulation_factor: [ 4, 4 ]
      mask_modulation_factor: [ 1, 1 ]
      weight_modulation_factors: [ [ 4, 4 ] ]
      wd: 0.00001
    Full:
      initial_lr: 0.001
      milestones: [ 15, 30 ]
      optimizer: Adam
      learnable_downsample: True
      threshold: 0.005
      bs: 32
      epochs: 30
      weight_modulation_factor: [ 4, 4 ]
      mask_modulation_factor: [ 1, 1 ]
      weight_modulation_factors: [ [ 4, 4 ] ]
      wd: .0
    Modulation:
      initial_lr: 0.01
      milestones: [ 15, 30 ]
      optimizer: Adam
      learnable_downsample: True
      weight_modulation_factor: [ 5,5 ]
      weight_modulation_factors: [ [ 4,4 ] ]
      mask_modulation_factor: [ 1, 1 ]
      threshold: 0.005
      bs: 32
      epochs: 30
      interpolation: bicubic
      factor: .1
      wd: .0
      reg: 0.00001
    Classifier_Only:
      initial_lr: 0.001
      milestones: [ 15, 30 ]
      optimizer: Adam
      learnable_downsample: True
      weight_modulation_factor: [ 5,5 ]
      weight_modulation_factors: [ [ 4,4 ],[ 9,9 ] ]
      mask_modulation_factor: [ 1, 1 ]
      threshold: 0.005
      bs: 32
      epochs: 30
      interpolation: bicubic
      num_blocks: [ ]
      groups: [ ]
      wd: .0
    LWF:
      initial_lr: 0.0001
      milestones: [ 15, 30 ]
      optimizer: Adam
      weight_modulation_factor: [ 6,6 ]
      threshold: 0.005
      bs: 32
      epochs: 30
      wd: 0.0
      interpolation: bicubic
      reg: 30000
  ImageNet:
    Full:
      initial_lr: 0.0001
      milestones: [ 15, 30 ]
      optimizer: Adam
      learnable_downsample: True
      weight_modulation_factor: [ 4,4,1,1 ]
      weight_modulation_factors: [ [ 4,4 ] ]
      mask_modulation_factor: [ 1,1 ]
      threshold: 0.005
      reg: .0
      wd: .0
      factor: .1
      bs: 32
      epochs: 30
      interpolation: bicubic
